services:
  - type: web
    name: examen-online
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/app.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.vvvqqvdwbltpkbwezyop:Correcaminos2026Batioja@aws-1-us-west-1.pooler.supabase.com:6543/postgres
