services:
  - type: web
    name: examen-online
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/app.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:correcamino%401@db.vvvqqvdwbltpkbwezyop.supabase.co:5432/postgres
